const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict'), path = require('node:path'), fs = require('node:fs');
const root = path.resolve(__dirname, '../..'), out = path.join(root, 'artifacts/electron/update-ui');
fs.mkdirSync(out, { recursive: true });
const env = { ...process.env, SOUNDSHREDDER_DESKTOP_HOME: path.join(out, 'profile') };delete env.ELECTRON_RUN_AS_NODE;
(async () => {
  const app = await electron.launch({ args: [path.join(__dirname, 'update-ui-app.cjs')], env });
  try {
    const workspace = await app.firstWindow(), errors = [];
    workspace.on('pageerror', error => errors.push(error.message));
    await workspace.locator('#updates').waitFor();
    const window = app.waitForEvent('window');await workspace.locator('#updates').click();const panel = await window;
    panel.on('pageerror', error => errors.push(error.message));
    await panel.waitForFunction(() => document.querySelector('#status').textContent === 'available');
    assert.equal(await panel.evaluate(() => typeof require), 'undefined');
    await panel.locator('#release-notes summary').click();
    assert.equal(await panel.locator('#notes img').count(), 0);assert.equal(await panel.evaluate(() => window.injected), undefined);
    assert.equal(await panel.locator('#notes').textContent(), 'Useful changes.');
    assert.match(await workspace.locator('#updates').textContent(), /1.3.0 available/);
    await panel.screenshot({ path: path.join(out, 'available.png') });
    await panel.locator('#primary').click();await panel.waitForFunction(() => document.querySelector('#status').textContent === 'downloading');
    await app.evaluate(() => qa.updater.emit('download-progress', { percent: 42, transferred: 52000000, total: 125000000 }));
    assert.match(await panel.locator('#transfer').textContent(), /42%/);
    await panel.screenshot({ path: path.join(out, 'downloading.png') });
    await panel.locator('#later').click();assert.equal(await app.evaluate(() => qa.installs), 0);
    const reopening = app.waitForEvent('window');await workspace.locator('#updates').click();const again = await reopening;
    await again.locator('#cancel').click();await again.waitForFunction(() => document.querySelector('#status').textContent === 'available');
    await again.locator('#primary').click();await again.waitForFunction(() => document.querySelector('#status').textContent === 'downloading');
    await app.evaluate(() => qa.complete([]));await again.waitForFunction(() => document.querySelector('#status').textContent === 'downloaded');
    assert.equal(await workspace.evaluate(async () => { try { await window.soundshredderDesktop.updateAction('install');return false; } catch { return true; } }), true);
    await workspace.evaluate(() => { window.allowUpdate = false;window.soundshredderDesktop.beforeUpdate(() => window.allowUpdate); });
    await again.locator('#primary').click();
    await again.waitForFunction(() => document.querySelector('#message').textContent.startsWith('Finish or cancel'));
    assert.equal(await app.evaluate(() => qa.stops), 0);
    await workspace.evaluate(() => { window.allowUpdate = true; });
    await app.evaluate(() => { qa.busy = true; });await again.locator('#primary').click();
    await again.waitForFunction(() => document.querySelector('#message').textContent.startsWith('Finish or cancel'));
    assert.equal(await app.evaluate(() => qa.installs), 0);
    await app.evaluate(() => { qa.busy = false; });await again.locator('#primary').click();
    await again.waitForFunction(() => document.querySelector('#status').textContent === 'installing');
    assert.equal(await app.evaluate(() => qa.installs), 1);
    await app.evaluate(() => qa.updater.emit('error', Error('Install failed')));
    await again.waitForFunction(() => document.querySelector('#status').textContent === 'error');
    await workspace.locator('#updates').waitFor();
    assert.ok(await app.evaluate(() => qa.recovered >= 2));
    await again.locator('#later').click();
    assert.deepEqual(errors, []);
    console.log('Native update UI passed: IPC isolation, safe release notes, sidebar status, progress, Later/reopen, cancellation, busy-job protection and install-failure recovery.');
  } finally { await app.close(); }
})().catch(error => { console.error(error);process.exitCode = 1; });
